# Định nghĩa cấu hình chung (anchor)
default_clickhouse: &default_clickhouse
  type: clickhouse
  driver: http
  host: clickhouse
  port: 8123
  user: admin
  password: "123456"
  secure: false
  verify: false
  threads: 4
  connect_timeout: 10
  send_receive_timeout: 300

# Profile 2
ecom_intermediate:
  target: dev
  outputs:
    dev:
      <<: *default_clickhouse
      database: ecom_db_intermediate


